sudo: false
language: python
python:
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- python create_local_settings.py
- python manage.py migrate
notifications:
  email: false
after_success:
  coveralls
